### ISSUE TITLE
Feature-Request: Support Object De-Structuring from "process" and "process.env"

### ISSUE THREAD

**Issue by aaronclong** [Andarist/rollup-plugin-dotenv#17]
### Currently
-----

[Object Destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) is a super common practice for developers, and it is fairly well supported by all recent runtimes.

However, destructing from `process` or `process.env` doesn't cause replacement. It was wondering if something could be done to make this possible. 

Could a proxy object be inject or another means to support destructuring from these object?

#### Example
```js
const { NODE_ENV, SUPER_ENV } = process.env
```

**Comment by Andarist** [comment]
I don't plan to support this. Destructuring `process.env` breaks static analysis in some ways. For instance, this might redundantly add `process` polyfills to some webpack bundles by default. It's a common requirement to require the replacement string to be written as-is in the source code.

**Comment by aaronclong** [comment]
@Andarist I think that depends on how you do it as well as if it is default. It can be made an opt-in feature.

Can you specify the "common requirement to require the replacement string to be written as-is in the source code"? 
Furthermore, destructoring wouldn't require changing the name. It is an option but not the requirement.

**Comment by Andarist** [comment]
This plugin doesn't do any fancy static analysis. It's literally a wrapper over [`@rollup/plugin-replace`](https://github.com/rollup/plugins/tree/8550c4b1925b246adbd3af48ed0e5f74f822c951/packages/replace). Even for that reason alone, I don't want to work on this as it requires non-trivial work and I just don't have any stake in it. It's just a little plugin I shared with the community in the past but it was created to serve my needs. What it does is completely sufficient to me.
