### ISSUE TITLE
process not defined

### ISSUE THREAD

**Issue by Tobbe** [Andarist/rollup-plugin-dotenv#7]
Hi

I started using this plugin when building my app locally, so in dev mode, and it worked great! (It's a StencilJS app.) But when I try to build for production no replacement is taking place and instead I get a "process not defined" error when trying to use my app.

So I tried switching over to @rollup/plugin-replace and that works. But I'd much rather use your plugin :)  

This is the code that uses the env var
```ts
  private static getBaseUrl(url: string) {
    if (url.indexOf("http") === 0) {
      // Urls that start with http probably have a host in them, and should not
      // have an extra base added
      return "";
    }

    return process.env.API_BASE;
  }
```

This is my config with rollup-plugin-dotenv. This does not work. No replacement is made.
```ts
import { Config } from "@stencil/core";
import dotenvPlugin from "rollup-plugin-dotenv";
import replace from "@rollup/plugin-replace";

export const config: Config = {
  namespace: "test-webcomponents",
  outputTargets: [
    {
      type: "dist",
      esmLoaderPath: "../loader",
    },
    {
      type: "dist-custom-elements-bundle",
    },
    {
      type: "docs-readme",
    },
    {
      type: "www",
      serviceWorker: null, // disable service workers
    },
  ],
  plugins: [dotenvPlugin()],
};
```

If I use plugin-replace instead it works (only showing the plugin config part) (But it only works on my build server. Of course this doesn't work locally with my .env file)
```ts
  plugins: [
    replace({
      "process.env.API_BASE": '"' + process.env.API_BASE + '"',
    }),
  ],
```

Locally I've been using a `.env` file, but when building for prod I'm setting an actual env var on the build server.

Can you see if I'm doing anything wrong?

**Comment by Andarist** [comment]
I'm glad that you have figured it out 👍

**Comment by TheMaikXX** [comment]
Hello,
I have basically same issue but I dont think I fully understand how the configuration values are meant to be provided given this conversation mentioning "system env vars"..
The weird part of it is that it works fine locally (running `npm run dev` with `NODE_ENV=dev` and `npm run build` with `NODE_ENV=prod`).
But when I make push and trigger CI/CD (it runs `npm i`, `npm run build`) the replacement does not happen and resulting bundle contains `process.env.TOAST_TIME_OUT`

I have rollup plugin at the beggining:
![image](https://user-images.githubusercontent.com/30082602/143148338-821d8d72-19e1-4c66-b647-d634f492f63d.png)

With this in `.env`:
```
TOAST_TIME_OUT=3000
TOAST_EXTENDED_TIMEOUT=1000
```
Plus I have `.env.dev` and `.env.prod` (with different config keys)

`NODE_ENV` is provided like so:
![image](https://user-images.githubusercontent.com/30082602/143148769-f60c7b5c-c043-4bc4-988d-d49df86a368b.png)

Any help would be appreciated
