### ISSUE TITLE
Update dependencies and provide option to pass options to dotenv and @rollup/plugin-replace

### ISSUE THREAD

**Issue by ShivamS136** [Andarist/rollup-plugin-dotenv#8]
#### Feature Request

|Package|Version Used|Current Version|
|----|----|----|
|@rollup/plugin-replace|^2.3.2|4.0.0|
|dotenv|^8.2.0|16.0.0|

As we can see there are major changes as well. 

Also, we are continuously having a warning mentioned in the pull request #5 so instead of passing particular options in this package, we can create two new options as `dotenv:` and `replace:` in config options. Value of these options will be directly passed to the packages `dotenv` and `@rollup/plugin-replace`. This will help in future releases as well.

**Comment by Andarist** [comment]
I've just pushed out some commits to update dependencies.
